# Generated by Django 4.1.3 on 2022-12-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderplaced", name="product",),
        migrations.AddField(
            model_name="orderplaced",
            name="product",
            field=models.ManyToManyField(to="app.product"),
        ),
    ]
