# Generated by Django 4.1.3 on 2022-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_orderplaced_product_orderplaced_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="product",),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(to="app.product"),
        ),
    ]
