# Generated by Django 4.1.3 on 2022-12-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_cart_product_cart_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(related_name="cart_prod", to="app.product"),
        ),
        migrations.AlterField(
            model_name="orderplaced",
            name="product",
            field=models.ManyToManyField(related_name="or_pl_prod", to="app.product"),
        ),
    ]
