# Generated by Django 4.1.3 on 2022-11-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="quizquestion", name="category",),
        migrations.DeleteModel(name="Quizcategory",),
    ]
